config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "/tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      # give the form back again -> new.html.erb
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    # No need for app/views/restaurants/update.html.erb
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

private

def task_params
  params.require(:task).permit(:title, :details, :completed)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
   <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<div class= "container mt-5">
<H1>My tasks</H1>

  <% @tasks.each do |task| %>
  <p><%= check_box_tag 'completed', '1', task.completed %> <%= link_to task.title, task_path(task) %>  <%= link_to '🗑️', task_path(task), class: 'btn btn-light', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }  %>
</p>
  <% end %>


<p><%= link_to("+Add a new task", "tasks/new") %></p>
</div>

app/views/tasks/new.html.erb
<div class= "container mt-5">
<h1>New Task</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control"%>
  <%= f.label :details %>
  <%= f.text_field :details, class: "form-control" %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <div class="mt-2">
  <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/tasks/show.html.erb
<div class= "container mt-5">
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p>  <%= check_box_tag 'completed', '1', @task.completed %>
  <%= label_tag 'completed', 'Completed' %></p>

<button  class= "btn btn-primary"> <%= link_to("edit task", edit_task_path(@task), class: "text-white") %></button>
<%# <%= link_to("edit task", "/tasks/#{@task.id}/edit") %>
<p><%= link_to '🗑️', task_path(@task), class: 'btn btn-light', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }  %></p>
<%= link_to("<- Back to task list", tasks_path) %>
</div>